### ISSUE TITLE
Cannot find DotNetUtilities in BouncyCastle.NetCore

### ISSUE THREAD

**Issue by Korporal** [bcgit/bc-csharp#113]
I'm struggling to leverage numerous published code sample in a .Net Core Web App.

For example creating a [`RSQCryptoServiceProvider` form a raw PEM](https://stackoverflow.com/questions/11346200/reading-pem-rsa-public-key-only-using-bouncy-castle/11367152) string.

The reason is that I cannot find (like this person [also posted](https://stackoverflow.com/questions/48326630/bouncycastle-netcore-impossible-to-find-dotnetutilities) about) any hint of the `DotNetUtilities `class.

Can anyone suggest anything?

**Comment by Loreno10** [comment]
Is there actually a solution? How to do:
rsaParams = DotNetUtilities.ToRSAParameters(privateRsaParams);

**Comment by peterdettman** [comment]
It's not clear what version of the library you are using. It should be in Org.BouncyCastle.Security namespace. Possibly DotNetUtilities is missing because it has been compiled with one of the flags that disables it:
    #if !(NETCF_1_0 || SILVERLIGHT || PORTABLE)

I suggest copying the method(s) you need from the source code:
    https://github.com/bcgit/bc-csharp/blob/master/crypto/src/security/DotNetUtilities.cs

Of course, you may find some of the methods won't compile/work (which would explain why it's missing in your platform/version), in which case you may need to find an alternative way to convert b/w BC and .NET types.

**Comment by RussKie** [comment]
After installing BouncyCastle.NetCore v1.8.2 from [NuGet](https://www.nuget.org/packages/BouncyCastle.NetCore/1.8.2) I'm getting this:
![image](https://user-images.githubusercontent.com/4403806/43754144-85773a2a-9a4c-11e8-9ee9-f6289b99ff64.png)


The library is referenced correctly:
![image](https://user-images.githubusercontent.com/4403806/43754090-3e91e826-9a4c-11e8-9735-53c6208630b8.png)


I can see the assembly in the local NuGet cache, however VS is having troubles resolving it
![image](https://user-images.githubusercontent.com/4403806/43753949-a06a45b2-9a4b-11e8-9b17-7d6b54e0e0a4.png)

**Comment by johnhargrove** [comment]
To anyone else who lands here like I did -- the issue is that `BouncyCastle.NetCore` is packaged by someone else. Don't use it. The package you want is `Portable.BouncyCastle`

**Comment by RussKie** [comment]
It would be great if the repo owners chimed on this issue. 😕

**Comment by johnhargrove** [comment]
Yeah, that would help. Because now that I'm using Portable.BouncyCastle, the class is present, but it's not actually working on non-Windows platforms, as it's relying on the `RsaCryptoServiceProvider` constructor that accepts a `CspParameters` object, which results in a crash on Linux:

```
System.PlatformNotSupportedException: 'CspParameters' requires Windows Cryptographic API (CAPI), which is not available on this platform.
```

After I collect more information (and verify that I'm not crazy), I will open a separate issue for this.

**Comment by reathh** [comment]
> To anyone else who lands here like I did -- the issue is that `BouncyCastle.NetCore` is packaged by someone else. Don't use it. The package you want is `Portable.BouncyCastle`

@johnhargrove Thank you very much for this! Sad that 17 days have passed, but your new issue isn't addressed.
