### ISSUE TITLE
x509 certificates that could be read in 1.8.1 can no longer be read by 1.8.3

### ISSUE THREAD

**Issue by jburger** [bcgit/bc-csharp#158]
I'm having some difficulty with certain x.509 certificates, when reading with version `1.8.3` - manifesting in an Exception that was introduced as part of an 'extra data' check. 

I believe the change the effects us is https://github.com/bcgit/bc-csharp/commit/374564ba8b2b385c90633679aae9cca27d0bb069 

It appears to be related to a version number and a subsequent check for 'extra data' - which fails. 

Here is a typical stack trace of `1.8.3` during certificate read:

```
Org.BouncyCastle.Security.Certificates.CertificateException: Failed to read certificate ---> System.ArgumentException: version 1 certificate contains extra data
at Org.BouncyCastle.Asn1.X509.TbsCertificateStructure..ctor(Asn1Sequence seq)
at Org.BouncyCastle.Asn1.X509.TbsCertificateStructure.GetInstance(Object obj)
at Org.BouncyCastle.Asn1.X509.X509CertificateStructure..ctor(Asn1Sequence seq)
at Org.BouncyCastle.Asn1.X509.X509CertificateStructure.GetInstance(Object obj)
at Org.BouncyCastle.X509.X509CertificateParser.ReadDerCertificate(Asn1InputStream dIn)
at Org.BouncyCastle.X509.X509CertificateParser.ReadCertificate(Stream inStream)
--- End of inner exception stack trace ---
at Org.BouncyCastle.X509.X509CertificateParser.ReadCertificate(Stream inStream)
at Org.BouncyCastle.OpenSsl.PemReader.ReadCertificate(PemObject pemObject)
```

Here is an example of a certificate that causes the exception:
```
-----BEGIN CERTIFICATE-----
MIIDAjCCAeoCFB+M5Oi9qfGrPikV/d44DfLCVMDuMA0GCSqGSIb3DQEBCwUAMC4x
CzAJBgNVBAYTAlVTMQwwCgYDVQQKDANYWFgxETAPBgNVBAMMCE15IENBIFYzMB4X
DTE4MTAyMzA4MjQzOFoXDTI4MTAyMDA4MjQzOFowLjELMAkGA1UEBhMCVVMxDDAK
BgNVBAoMA1hYWDERMA8GA1UEAwwITXkgQ0EgVjMwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQC2ATfFRW9oM3Yz10EEIVcRlOnfPsQQBT9Z7GKuP5MKZAI1
CHX9ujf1A/EeKBHtCTU5q7TLtRIpAfFVJj7KynSqcN9SzXBvvyIX82VienV4S4XK
ywiY0yfmeVFZy2IQz2o5vm+Al+jzBm200rwPtadHy0z4xsLy7ly1K1fd828Ui9pB
nCaeuoih4n2GSpqgNIHnlkHGwmWYeryveXpSsWJYodQroNl89usHqRXlH0alVpQs
Tfk+LNoiDGwTdRZFeLYo/Rqw0iSvCNgSULrK2TpT4ZNHe6HIr9I2t9fNUvf0J9bG
EJrL1K7Gh2V85dcYBs/0Nh+eFs7Hp5Ua0JlxCufjAgMBAAGjHTAbMAwGA1UdEwQF
MAMBAf8wCwYDVR0PBAQDAgEGMA0GCSqGSIb3DQEBCwUAA4IBAQASQ6195ALx1Mfs
ZXF5OqBKC6DR0d4UC/pxth5xpl5wM5FpiH/bMUIqzKLEvyV3ZMZ4UyPC+tn5k+gs
HAwUJpZDKKmzhgZbmeuwNbRk3H5NRjQ3do2jwneDdIGAI8DtjOlEOtbkfO0xDxP/
UM7EUt3/Lk6SxPhoDep7MdkWzJkpjzPzz3UO/nGNTfGOJza2pTIV+h7oKGpnxkdX
4oJOLBa1C4ONDQQOCYpC2O+66p/j5YGIY/ifuxviPItYk8DZR2YgNC7vRuVMBXAz
wY48OlOW+ybmolmMO4Hg19BT45zJLEqF/Sju+e+QZHMHTe5jen76cA3RZxdQ656w
wj47Z+DO
-----END CERTIFICATE-----
```

I can share some code that was used to generate this certificate if that aids tracking down the issue.

This certificate can be read in 1.8.1:
![image](https://user-images.githubusercontent.com/579657/47350996-9edb2780-d6fe-11e8-8dbc-13e40eada692.png)

The windows certificate store and openssl seem to be OK with this certificate, so I'm hoping that I could get some advice on whether there is something wrong with this certificate, or if there is an issue in these new checks that needs further thought?

Thanks!

**Comment by peterdettman** [comment]
The issue is that the (absent because == default) version indicates a V1 certificate, but there are extensions present (the "extra data") in the ASN.1 sequence, which is a feature added for V3. Given that the purported issuer is "My CA V3" I would guess the certificate creator was trying to create a V3 CA cert, but the version was not set correctly.

**Comment by jburger** [comment]
Thanks @peterdettman I can confirm that by explicitly setting a version number using the code sample I have, it now passes the validation check and correctly identifies the certificate as a V3 certificate.

**Comment by LarryRothOakton** [comment]
Hi @peterdettman I'm a software developer for a consulting company. We are currently building a medical system for the Red Cross Blood Service in Australia that manages organ transplants. We rely on on software that @jburger produces to deploy our application. When our application goes into production next year, it could result in life or death if it does not function correctly or we are blocked from deploying critical fixes.

For this issue, I consider it irresponsible to deploy a breaking change for a minor release from 1.8.1 to 1.8.3 that could have potential downstream effects. We're lucky in this instance that the affected certificate (which does have a configuration error) is currently not in use and that our system is not in production yet.

If a breaking change like this is implemented, there should be the option to revert to the old behaviour with some flags in the method calls in order to support existing artefacts. Environment such as ours could require advanced warning and time to sort this out and regenerate certificates.

Our client is very sensitive to any defects, especially those that could bring our software "assembly line" to a halt.

Hoping this can be addressed soon!

Thanks!

**Comment by bcgit** [comment]
Hi Larry, I've no doubt @jburger will be able to fix his software. We're happy to hear that this change has avoided invalid certificates from being deployed to production. I would stress that we are not the only people who have been tightening up validation on these.
