### ISSUE TITLE
Bug in crypto/src/security/SecureRandom.cs NextDouble implementation

### ISSUE THREAD

**Issue by bkalakrishnan** [bcgit/bc-csharp#253]
The Contract for Random.NextDouble is "Returns a random floating-point number that is greater than or equal to 0.0, and less than 1.0". However in your implementation of SecureRandom, NextDouble can return 1.0 when the 64 bit random number returned by the generator is close to 0xFFFFFFFFFFFFFFFF and this breaks the API contract. This is because doubles have only 53 bits of precision, and so the division result for 1024 of the highest 64 bit unsigned integers will get rounded up to 1.0. 

To avoid this you should use only 53 bits of the PRNG output and divide the number by 2^53 (Or multiply by 2^-53). Please see the Java implementation at https://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/util/Random.java (lines 493 to 533)

Here is a program that demonstrates this error.

````
using System;

namespace bugtest
{
    class MainClass
    {
        private static readonly double DoubleScale = System.Math.Pow(2.0, 64.0);
        private static readonly double One = 1.0;

        public static String DoubleToIEEE754Hex(double d)
        {
            byte[] bytes = BitConverter.GetBytes(d);
            return BitConverter.ToString(bytes);
        }

        public static void Main(string[] args)
        {
            long Rand = -1;
            int Count = 0;
            bool EqualsOne = false;
            Console.WriteLine("One is represented as : "+DoubleToIEEE754Hex(One));
            Console.WriteLine();
            Console.WriteLine("Long                Double Returned");
            double d = 0;
            do
            {
                // The Conversion as performed in NextDouble implementation
                d = Convert.ToDouble((ulong)Rand) / DoubleScale;
                EqualsOne = (d == One);
                if (EqualsOne)
                {
                    if (Count < 5)
                    {
                        Console.WriteLine(Rand.ToString("X") + "   " + DoubleToIEEE754Hex(d));
                    } else
                    {
                        Console.Write(".");
                    }
                    Count++;
                    Rand--;
                }
            } while (EqualsOne);
            Console.WriteLine();
            Console.WriteLine(Rand.ToString("X") + "   " + DoubleToIEEE754Hex(d));
            Console.WriteLine("Number of long values for which output was equal to 1.0 = " + Count);
        }
    }
}
````

**Comment by peterdettman** [comment]
Thanks for reporting. Fixed in our git repo, please check once mirrored to GitHub.

**Comment by peteroupc** [comment]
I want to note the following:

1.  In security applications, floating-point numbers are hardly ever used.  The only two exceptions I am aware of are differential privacy and lattice-based cryptography.  And at least in differential privacy, where floating-point numbers are used, all numbers the format can represent have to have the correct probability or a catastrophic loss of privacy results (Mironov, I., "On Significance of the Least Significant Bits For Differential Privacy", 2012).  This, however, cannot be achieved merely by multiplying or dividing a uniform random number by a constant (Goualard, F., "[Generating Random Floating-Point Numbers by Dividing Integers: a Case Study](https://hal.archives-ouvertes.fr/hal-02427338/)", 2020).  And even in these two security applications, there are ways to avoid random floating-point numbers.

2.  On the other hand, an algorithm to produce all representable floating-point numbers with the correct probability will generally have variable running time, mainly because it relies on rejection sampling.  (I have written one such algorithm, and I will give a link to it if there is interest.) In general, however, a variable-time security algorithm is vulnerable to timing side-channel attacks, especially if the algorithm reuses secrets.

**Comment by peterdettman** [comment]
Thanks, @peteroupc . In fact we do not use this method (`NextDouble`) within the project; it's an incidental method on System.Random. We'd consider throwing "NotSupported" here but there is also backward compatibility to worry about. Since the commit is slow to mirror, the code has been changed as below; your thoughts are welcome.

```
private static readonly double DoubleScale = 1.0 / Convert.ToDouble(1L << 53);
public override double NextDouble()
{
    ulong x = (ulong)NextLong() >> 11;
    return Convert.ToDouble(x) * DoubleScale;
}

```

**Comment by bkalakrishnan** [comment]
Thanks, @peterdettman. Looks good to me.
