### ISSUE TITLE
GetEncoded() behavior changed in 1.9.0

### ISSUE THREAD

**Issue by Norikv** [bcgit/bc-csharp#355]
`GetEncoded()` method returns different data for `Asn1Object` instance and for `SignerInfo` instance even when both instances were created from the same bytes. In other words, `SignerInfo.GetEncoded()` != `Asn1Object.GetEncoded()` for the same ASN.1 structure. The problem was not yet present in 1.8.10.

Is there any reason for this change or is it unintentional?

Minimal complete reproducible example that produces different results in BouncyCastle 1.8.10 and 1.9.0:

```csharp
using System;
using System.Linq;

namespace SignerInfo
{
    class Program
    {
        static void Main(string[] args)
        {
            byte[] testData = Convert.FromBase64String(@"MIICBgIBATAyMCYxCzAJBgNVBAYTAlNLMRcwFQYDVQQDEw5TaWduZXJJbmZvVGVzdAIIWwDByhkzZUUwCwYJYIZIAWUDBAIBoGkwGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMjIwNDA0MTUwNzMzWjAvBgkqhkiG9w0BCQQxIgQg8oHnZcZVznmGF1Hyz1zQ6DHtujkplvgdNK6bpRhbcpQwDQYJKoZIhvcNAQEBBQAEggEAEMo2LkqbI7ZmtuzXgrXeF2kAXbIR/vSNNXfeggvZS1TC1xQojcclzc6WkgqcnryQngQKL7P39Dw+zjkTnr/fmxnaFlCbATMOSjRCwlV8HFoxsEffXzqSRJix4PndomicVHujKz6UP5NRK3mY2MtU9y+bzhV4A4xKdXJXGBc4Wnsy30MMvqHpskxvat5uc9A77oFQhLkVKplLdZ0e+8QFcoA/Y0pWRuDsfgDQyIlty2tODle5kMNSKoFThCrNZs1zuNsNNd9HVkEMIn09Nlw8jTTNRhFPJqCHmtLiWFc1jH6cdSpE8AutKySGv+18a5BxQojM+DaXC2Jd9VflPkXTPqFCMBUGBSoDBAUKMQwECgABAgMEBQYHCAkwGwYFKgMEBRQxEgQQAAECAwQFBgcICQoLDA0ODzAMBgUqAwQFHjEDBAEB");

            var asn1Object = Org.BouncyCastle.Asn1.Asn1Object.FromByteArray(testData);
            byte[] asn1ObjectEncoded = asn1Object.GetEncoded();

            var signerInfo = Org.BouncyCastle.Asn1.Cms.SignerInfo.GetInstance(asn1Object);
            byte[] signerInfoEncoded = signerInfo.GetEncoded();

            if (!asn1ObjectEncoded.SequenceEqual(signerInfoEncoded))
                throw new Exception("Encoded Asn1Object does not match encoded SignerInfo");
        }
    }
}
```

Viewing both `GetEncoded()` return values in Asn1Editor, we can see the different order of items in `SET` of unsigned attributes:

![image](https://user-images.githubusercontent.com/90982672/161761522-1b12c753-2f4e-47c9-bef4-ece971894c69.png)

**Comment by peterdettman** [comment]
SignerInfo actually parses the ASN.1 object and then creates a new one when encoding. There's no contract to reproduce the input encoding.

What changed with 1.8.10 is that our ASN.1 encoder for Der... types (e.g. DerSequence) now forces DER encoding on the whole subtree. Since SignerInfo actually encodes with a DerSequence, GetEncoded now produces a full DER encoding (as if GetDerEncoded were called).

SignerInfo also knows that the CONTEXT SPECIFIC entry at the end of the top-level sequence is supposed to be a SET (it's implicit), which the ASN.1 decoder alone can't know (since it hasn't been told the ASN.1 syntax it's parsing). So when it produces the DER encoding, it also sorts that SET (per the rules for the canonical DER ordering); the entry that moves does so because its overall length is shorter than the other sequences, so it sorts earlier.

Even asn1Object.GetDerEncoded() won't be equal to the SignerInfo encoding, because it has no way to know there is an implicit SET there that needs sorting.

**Comment by Norikv** [comment]
Thank you for the explanation. However, it is still a change in behavior that I need to react to. So what is your conclusion? Will this issue be addressed in any way or will it simply be closed?

**Comment by peterdettman** [comment]
It will be closed (not a bug). Unfortunately this is Hyrum's Law in action. Using a DER encoding for SignerInfo.GetEncoded() is not contract-breaking from our POV. All DER encodings are valid BER encodings too.

The equality of the two encodings involved in this case was only coincidental; in particular it was already not true for many other subclasses of Asn1Object, and also not true for GetDerEncoded(). So there would be little point in making this special case a rule (especially since there is already this release that violates it).

**Comment by Norikv** [comment]
Thank you for your assistance. I'm closing the issue.
