### ISSUE TITLE
TLS_RSA_WITH_RC4_128_MD5

### ISSUE THREAD

**Issue by zivillian** [bcgit/bc-csharp#411]
For an old IOT device I needed the cipher TLS_RSA_WITH_RC4_128_MD5, so I added a `TlsRc4Cipher`. Are you interested in a PR?

I know that this Cipher is deprecated/forbidden in RFC 7465, but there may be more old devices which only support old ciphers.

**Comment by Dezzj** [comment]
https://github.com/bcgit/bc-csharp/issues/411#issue-1515518426

**Comment by Dianna52** [comment]
Can someone tell me what the he double hockey sticks is going on. I have literally no clue what is going on I thought for sure this was going to be my break though but I'm more confused than  ever. 
Thank you 
Dianna Duran

**Comment by Dezzj** [comment]
Yes so am I I have no clue

Dessirae Thompson

**Comment by peterdettman** [comment]
We cannot add the cipher, and of course we recommend against using these ciphers at all.

However I have resurrected the registry entries for TLS_RSA_WITH_RC4_128_MD5 (and TLS_RSA_WITH_RC4_128_SHA) so that you can add a custom `BcTlsCrypto` subclass in order to dynamically use your own implementation. This change will be released in 2.1.0 shortly.

Your subclass of `BcTlsCrypto` should at minimum override `CreateCipher` and `HasEncryptionAlgorithm`. You may also prefer to override `HasMacAlgorithm` and `CreateHmac` to avoid surprises in case we completely remove MD5 support at some point.
