### ISSUE TITLE
Cleanup repository

### ISSUE THREAD

**Issue by Genbox** [bcgit/bc-csharp#46]
The repository could use some cleaning up in terms of naming and solution files.
I would recommend the following changes:
- Delete csharp.sln as it is for an old version of Visual Studio (VS2015 Community is free)
- Delete the crypto-test and crypto.tests.Net45 projects as they are no longer needed. Test Explorer, Resharper and so on have test discovery and can run all tests directly from VS2015. For everyone else, the tests are built to be run as console applications.
- Rename the "crypto" project files to BouncyCastle instead.
- Have common naming on project files such as "BouncyCastle.DotNet45", "BouncyCastle.PCL", "BouncyCastle.iOS". Only small adjustments are needed as some project files already follow this naming.

Having these changes just makes it a lot easier to identify what you are working with as a contributor.

**Comment by peterdettman** [comment]
I realise things are a bit of a mess, but we definitely intend to clean things up along the lines you describe. We needed to keep the old versions around to ensure any 1.7 users could upgrade as painlessly as possible; they will be dropped in the near future (in master, kept on a 1.8.x branch). We also want to reorganise the build, and consolidate the solution/project files; we went with the kitchen sink approach to avoid any further delays in getting 1.8.0 out, and for easy transition by people who had been using the forks by @jstedfast or @onovotny. We still don't really have a clear picture of the full range of platforms that people want us to target in future. We'd obviously like to keep it within reason.

**Comment by ForNeVeR** [comment]
Was anything planned yet? I'm sorry, but the project's build as it is now is a mess. It is unclear what `*.sln` or `*.csproj` file is intended to be used for building the project. It seems that all of the `*.sln` files in the root of the repository are broken (because they include broken `*.csproj`), and most of the `*.csproj` are broken, too (i.e. they miss some of the `*.cs` files).

I had to load `crypto.Net45.csproj` and manually retarget it to .NET4.5 to be able to build anything. Probably some guidance about the build system in the README would help (e.g. what `*.sln` / `*.csproj` file I should load and what .NET targeting pack I should install; link to .NET 2.0 targeting pack would be helpful, too, because it's not that easy to find it these days).

**Comment by bcgit** [comment]
Sorry, you caught us in the middle of a release and not everything appears to have gotten over to the mirror. The repo should be in sync within the next couple of hours. Let us know if you have any further problems.
