### ISSUE TITLE
Ability to encode DerBoolean as 0x01

### ISSUE THREAD

**Issue by nmoinvaz** [bcgit/bc-csharp#484]
There is a similar request in golang repository [here](https://github.com/golang/go/issues/53932). We interact with a legacy parser that requires booleans encoded as 0x01. 
This [commit](https://github.com/bcgit/bc-csharp/commit/be15049124860ccb7335b92215e8b8dfa1821bf9) changed things by introducing `GetContents` which forces boolean to be encoded as 0xFF even though `DerBoolean(byte[] value)` might be passed as 0x01. 

https://github.com/bcgit/bc-csharp/blame/f6aab0be05a5a176771e865825fc5962b33a45c8/crypto/src/asn1/DerBoolean.cs#L157

We thought of overriding `DerBoolean`, but it doesn't seem possible.

**Comment by peterdettman** [comment]
`GetContents` only overrides the value if we are encoding as DER, because that is required (X.690 11.1):

> If the encoding represents the boolean value TRUE, its single contents octet shall have all eight bits set to one. (Contrast
> with 8.2.2.)

If encoding to BER instead it should use the provided value. It may not be that simple though since many of our ASN.1 types force DER encoding by default which affects their subcomponent encodings (and it would be difficult to rectify that).

I definitely recommend fixing the legacy parser, or switching to a new one, or if a third party is involved push the issue with them.

---

There is possibly some confusion at the golang repo in believing that certificates must be DER encoded. That is not generally the case, although there are a few specifications that explicitly require it and other software may do so by policy even if the relevant specification doesn't.

(Signers and verifiers are responsible for calculating over a DER encoding, which ought to mean either validation or re-encoding of the original encoding.)

**Comment by nmoinvaz** [comment]
> I definitely recommend fixing the legacy parser, or switching to a new one, or if a third party is involved push the issue with them.

The issue is with Apple's encoding of DER entitlements that is used in their codesigning process.

https://github.com/apple-oss-distributions/Security/blob/ef677c3d667a44e1737c1b0245e9ed04d11c51c1/OSX/utilities/der_plist.c
* [der_decode_boolean](https://github.com/apple-oss-distributions/Security/blob/ef677c3d667a44e1737c1b0245e9ed04d11c51c1/OSX/utilities/der_boolean.c#L35) seems to indicate that it would work properly with either 0xFF or 0x1.

* [der_encode_boolean](https://github.com/apple-oss-distributions/Security/blob/ef677c3d667a44e1737c1b0245e9ed04d11c51c1/OSX/utilities/der_boolean.c#L64) stores the value 0x1 or 0x0 returned from `CFBooleanGetValue(boolean)`.

I don't expect to get anywhere with bringing it up to Apple but I have as FB13270115. They are notorious for ignoring reported developer bugs. And even if they do acknowledge it who knows if they will fix it or when. 

Someone else has also run into the same issue with DER entitlements:
https://github.com/filipnavara/CodeSign/blob/3fc9033c6a82de3618754ce28ee86048d6a30930/Melanzana.CodeSign/PropertyList/DerPropertyListParser.cs#L72C27-L72C27
Though I think those code comments are backwards, in that it is stored as 0x1. And the fact that they are using BER to decode the boolean proves it.
