### ISSUE TITLE
SPHINCS+ key info encoding fails

### ISSUE THREAD

**Issue by nd1012** [bcgit/bc-csharp#521]
Exception:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'element')
```

Stack:

```
Asn1EncodableVector.Add(Asn1Encodable element)
Asn1EncodableVector.ctor(Asn1Encodable element)
AlgorithmIdentifier.ToAsn1Object()
Asn1OutputStream.GetContentsEncodings(Int32 encoding, Asn1Encodable[] elements)
DerSequence.GetEncoding(Int32 encoding)
Asn1Object.InternalGetEncoded(String encoding)
Asn1Encodable.GetEncoded(String encoding)
Asn1Encodable.GetDerEncoded()
```

Code to reproduce:

```cs
// Create a key pair
SphincsPlusKeyPairGenerator keyGen = new();
keyGen.Init(new SphincsPlusKeyGenerationParameters(new(), SphincsPlusParameters.haraka_256f_simple));
AsymmetricCipherKeyPair keys = keyGen.GenerateKeyPair();
SphincsPlusPrivateKeyParameters privateKey = keys.Private as SphincsPlusPrivateKeyParameters ?? throw new InvalidDataException("Invalid private key");
SphincsPlusPublicKeyParameters publicKey = keys.Public as SphincsPlusPublicKeyParameters ?? throw new InvalidDataException("Invalid public key");

// Private key info serialization (FAILS!)
byte[] serialized = PqcPrivateKeyInfoFactory.CreatePrivateKeyInfo(privateKey).GetDerEncoded();
_ = PqcPrivateKeyFactory.CreateKey(serialized) as SphincsPlusPrivateKeyParameters ?? throw new InvalidDataException("Deserialization of private key failed");

// Public key info serialization (FAILS also!)
serialized = PqcSubjectPublicKeyInfoFactory.CreateSubjectPublicKeyInfo(publicKey).GetDerEncoded();
_ = PqcPublicKeyFactory.CreateKey(serialized) as SphincsPlusPublicKeyParameters ?? throw new InvalidDataException("Deserialization of public key failed");
```

The same exception is being thrown, when I use `GetEncoded` instead (similar stack).

Am I doing it wrong - is there any other recommended (working) way to un-/serialize the keys?

By the way, the serilization worked with the example code above until the NuGet package was updated to version 2.3.0.

**Comment by roy-basmacier** [comment]
Hello @nd1012 , 

The error only occurs when using the following parameters
`SphincsPlusParameters.haraka_128f_simple`
 `SphincsPlusParameters.haraka_128s_simple`
 `SphincsPlusParameters.haraka_192f_simple`
 `SphincsPlusParameters.haraka_192s_simple`
 `SphincsPlusParameters.haraka_256f_simple`
 `SphincsPlusParameters.haraka_256s_simple`

This is because they weren't added to the[ look-up tables](https://github.com/bcgit/bc-csharp/blob/master/crypto/src/pqc/crypto/utils/PqcUtilities.cs) and the [converters](https://github.com/bcgit/bc-csharp/blob/master/crypto/src/pqc/crypto/utils/PqcPublicKeyFactory.cs).

I'll add them in a patch, however, NIST stated in their [FIPS 205 draft (line 306-308)](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.205.ipd.pdf) that they do not approve of these parameters.
>"This standard approves the use of only 12 of the 36 parameter sets defned in [4, 5]. As specifed
in Section 10, only the ‘simple’ instances in which the cryptographic functions are instantiated
with SHA-2 or SHAKE are approved. "
