### ISSUE TITLE
DerGeneralizedTime StackOverflowException

### ISSUE THREAD

**Issue by DizzyHSlightlyVoided** [bcgit/bc-csharp#60]
``` C#
DerGeneralizedTime time = new DerGeneralizedTime("20160601140601GMT-04:00");
```

... throws a StackOverflowException when it tries to call `DerGeneralizedTime.ToDateTime()` in the constructor. This happens because, when the string specifies a time zone instead of ending in "Z", `DerGeneralizedTime.ToDateTime()` first calls `GetTime()`, which calls `CalculateGmtOffset()` ... which calls `ToDateTime()`.

(I also notice that the time-zoned format follows the general form of `yyyyMMddHHmmss'GMT'zzz` -- that is, containing the literal text 'GMT' before the offset. This is incorrect; the ASN.1 specification says it should be `yyyyMMddHHmmsszzz`.)

**Comment by peterdettman** [comment]
Thanks for the report, I can reproduce the exception. It appears there needs to be an error raised if the +/- character is present, but not in one of the expected positions (because of the ':', which is invalid incidentally). The Java version, on which this is based, appears to have a similar issue (without the stack overflow).

Regarding the 'GMT', yes I think there's a problem there in that we could end up putting a string containing the 'GMT' into the ASN.1. The confusion seems to be caused by the presence of GetTime(), which is documented as using 'GMT' in the format, and various bits of common code are confused as to which format is in effect.

The constructor you're using is clearly intended to take a valid ASN.1 string directly though, so we'll fix the validation there, and review the rest of it. Thanks again.

**Comment by cipherboy** [comment]
As far as I can tell, this now correctly throws an invalid format `ArgumentException` and thus is fixed.
